ALTER TABLE FACULTIES
ADD CONSTRAINT FAC_CATEGORY CHECK(CATEGORY='Professor' OR CATEGORY='Assistant Professor' OR CATEGORY = 'Associate Professor');

ALTER TABLE DEGREE_TYPES
ADD CONSTRAINT DEG_TYPE_CLASS CHECK(CLASSIFICATION='Undergraduate' OR CLASSIFICATION='Graduate');

ALTER TABLE DEGREE_TYPES
ADD CONSTRAINT DEG_TYPE_YEAR CHECK(YEAR=1 OR YEAR=2 OR YEAR=3 OR YEAR=4);

ALTER TABLE STUDENTS
ADD CONSTRAINT STUD_SEX CHECK(SEX='M' OR SEX='F');

ALTER TABLE FACULTIES
ADD CONSTRAINT FAC_ID CHECK(FACULTY_ID LIKE 'F_%');

ALTER TABLE STUDENTS
ADD CONSTRAINT STUD_ID CHECK (STUDENT_ID LIKE 'S%');

ALTER TABLE FACULTIES
ADD UNIQUE(USER_ID);

ALTER TABLE STUDENTS
ADD UNIQUE(USER_ID);

COMMIT;

ALTER TABLE STUDENTS_CO_CAMERAS
ADD CONSTRAINT CAM_RET CHECK(RETURN_DATE>=ISSUE_DATE);

ALTER TABLE STUDENTS_CO_BOOKS
ADD CONSTRAINT S_BOOK_RET CHECK(RETURN_DATE>=ISSUE_DATE);

ALTER TABLE STUDENTS_CO_JOURNALS
ADD CONSTRAINT S_JOUR_RET CHECK(RETURN_DATE>=ISSUE_DATE);

ALTER TABLE STUDENTS_CO_CONFERENCE_PAPERS
ADD CONSTRAINT S_CP_RET CHECK(RETURN_DATE>=ISSUE_DATE);

ALTER TABLE FACULTIES_CO_CAMERAS
ADD CONSTRAINT F_CAM_RET CHECK(RETURN_DATE>=ISSUE_DATE);

ALTER TABLE FACULTIES_CO_BOOKS
ADD CONSTRAINT F_BOOK_RET CHECK(RETURN_DATE>=ISSUE_DATE);

ALTER TABLE FACULTIES_CO_JOURNALS
ADD CONSTRAINT F_JOUR_RET CHECK(RETURN_DATE>=ISSUE_DATE);

ALTER TABLE FACULTIES_CO_CONFERENCE_PAPERS
ADD CONSTRAINT F_CP_RET CHECK(RETURN_DATE>=ISSUE_DATE);

ALTER TABLE STUDENTS_RESERVES_ROOMS
ADD CONSTRAINT S_ROOM_RES CHECK(RESERV_END_TIME>=RESERV_START_TIME);

ALTER TABLE FACULTIES_RESERVES_ROOMS
ADD CONSTRAINT F_ROOM_RES CHECK(RESERV_END_TIME>=RESERV_START_TIME);

COMMIT;

